#!/bin/bash
#SBATCH --job-name=sctv.job
#SBATCH --output=/home/akathpalia/data/SupremeCourtTV/sctv_out.txt
#SBATCH --error=/home/akathpalia/data/SupremeCourtTV/sctv_err.txt
#SBATCH --time=2-00:00
#SBATCH --mem=50000
#SBATCH --gres=gpu:4

# # Test CUDA compiler (not needed by deep learning people, we just use the python libraries)
# /cm/shared/apps/cuda11.1/toolkit/11.1.1/bin/nvcc -o saxpy /home/akathpalia/cuda_c_code/saxpy.cu && ./saxpy

# Test nvidia-smi
nvidia-smi

# Test Python conda environment
source activate py38
/home/akathpalia/miniconda3/envs/py38/bin/python /home/akathpalia/data/SupremeCourtTV/src/sctv.py
# source /home/robalasubram/miniconda3/etc/profile.d/conda.sh
# conda activate /home/robalasubram/miniconda3/envs/py38
# /home/robalasubram/miniconda3/envs/py38/bin/python /home/akathpalia/data/SupremeCourtTv/src/sctv.py